services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password  # Zmień na prawdziwe hasło
      POSTGRES_DB: universal_server_database
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com  # Zmień na swój email
      PGADMIN_DEFAULT_PASSWORD: your_admin_password  # Zmień na prawdziwe hasło
    ports:
      - "8080:80"  # Dostępny na http://localhost:8080
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin

# Opcjonalny serwis dla appki Node.js
# app:
#  build: .
#  ports:
#    - "3000:3000"
#  depends_on:
#    - db
#  environment:
#   DATABASE_URL: "postgresql://postgres:twoje_haslo@db:5432/twoja_baza?schema=public"

volumes:
  postgres-data:
  pgadmin-data:  # Dodany volume dla persistencji danych pgAdmin